/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlktx;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class QLViPham extends javax.swing.JFrame {
    //private Dashboard dashboard;
    
    public QLViPham(){
        initComponents();
        loadData();
    }
    
private void loadData(){
    String manv = DangNhap.GlobalVariables.username;
    Connection con = QLKTX.getConnection();
    if(con == null) {
        JOptionPane.showMessageDialog(this,"Lỗi kết nối csdl","Lỗi",JOptionPane.ERROR_MESSAGE);
        return;
    }
        //tạo 1 table mới
        DefaultTableModel table = new DefaultTableModel();
        //gán cho table cột
        String title[] = {"Mã vi phạm","MSSV","Nội dung","Ngày vi phạm","Ngày lập vi phạm"};
        table.setColumnIdentifiers(title);
        try{                        
                String sql = "SELECT * FROM PHIEUVIPHAM P JOIN CUTRU C ON P.MSSV = C.MSSV"
                        + " JOIN PHONG ON C.MAPHONG=PHONG.MAPHONG"
                        + " JOIN TOA T ON PHONG.MATOA = T.MATOA"
                        + " WHERE T.MATRUONGTOA = ? ORDER BY MAVIPHAM";
                PreparedStatement pst = con.prepareStatement(sql);  
                pst.setString(1, manv);
                ResultSet rs = pst.executeQuery();
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                while(rs.next()){
                    String MaVP = rs.getString("MAVIPHAM");
                    String MSSV = rs.getString("MSSV");
                    String NoiDung = rs.getString("NOIDUNG");
                    Date NgayVP = rs.getDate("NGAYVIPHAM"); 
                    String ngayvp = sdf.format(NgayVP);
                    Date NgayLapVP = rs.getDate("NGAYLAPVP");
                    String ngaylapvp = sdf.format(NgayLapVP);
                    table.addRow(new Object[]{MaVP,MSSV,NoiDung,ngayvp,ngaylapvp});
                }
                
                //gán cho table chính
                tbDSViPham.setModel(table);
                //cho giá trị xuất hiện giữa bảng
                DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
                for (int i = 0; i < tbDSViPham.getColumnCount(); i++) {
                    tbDSViPham.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
                }  
                pst.close();
                rs.close();
                con.close();                     
        }catch(SQLException e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnHeader = new javax.swing.JPanel();
        javax.swing.JButton btBack = new javax.swing.JButton();
        lbWebDev = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel lbDSViPham = new javax.swing.JLabel();
        javax.swing.JLabel lbMSSV = new javax.swing.JLabel();
        javax.swing.JLabel lbNoiDung = new javax.swing.JLabel();
        javax.swing.JLabel lbNgayVP = new javax.swing.JLabel();
        txtMSSV = new javax.swing.JTextField();
        txtNoiDung = new javax.swing.JTextField();
        javax.swing.JButton btThem = new javax.swing.JButton();
        javax.swing.JButton btXoa = new javax.swing.JButton();
        javax.swing.JLabel lbTaoViPham = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDSViPham = new javax.swing.JTable();
        javax.swing.JLabel lbTimKiemVP = new javax.swing.JLabel();
        javax.swing.JButton btLocVP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dcTuNgay = new com.toedter.calendar.JDateChooser();
        dcDenNgay = new com.toedter.calendar.JDateChooser();
        txtNgayVP = new com.toedter.calendar.JDateChooser();
        cbLoai = new javax.swing.JComboBox<>();
        txtCbTim = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        javax.swing.JButton btViPham = new javax.swing.JButton();
        javax.swing.JButton btYeuCau = new javax.swing.JButton();
        javax.swing.JButton btDSSinhVien = new javax.swing.JButton();
        javax.swing.JLabel lbChucNang = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jbtttcn = new javax.swing.JButton();
        btthongbao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnHeader.setPreferredSize(new java.awt.Dimension(800, 80));

        btBack.setBackground(new java.awt.Color(254, 254, 254));
        btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Back.png"))); // NOI18N
        btBack.setBorder(null);
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        lbWebDev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.jpg"))); // NOI18N

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeader.setLayout(pnHeaderLayout);
        pnHeaderLayout.setHorizontalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btBack)
                .addGap(276, 276, 276)
                .addComponent(lbWebDev, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnHeaderLayout.setVerticalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(btBack)
                .addGap(23, 23, 23))
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addComponent(lbWebDev, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 490));

        lbDSViPham.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lbDSViPham.setForeground(new java.awt.Color(83, 160, 219));
        lbDSViPham.setText("Danh sách vi phạm");

        lbMSSV.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbMSSV.setText("MSSV");

        lbNoiDung.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbNoiDung.setText("Nội dung");

        lbNgayVP.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbNgayVP.setText("Ngày vi phạm");

        btThem.setBackground(new java.awt.Color(93, 163, 217));
        btThem.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btThem.setForeground(new java.awt.Color(255, 255, 255));
        btThem.setText("Tạo");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btXoa.setBackground(new java.awt.Color(93, 163, 217));
        btXoa.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btXoa.setForeground(new java.awt.Color(255, 255, 255));
        btXoa.setText("Xóa vi phạm");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        lbTaoViPham.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbTaoViPham.setText("Tạo vi phạm");

        tbDSViPham.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tbDSViPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã vi phạm", "MSSV", "Nội dung", "Ngày vi phạm", "Ngày lập vi phạm"
            }
        ));
        tbDSViPham.setRowHeight(40);
        jScrollPane1.setViewportView(tbDSViPham);

        lbTimKiemVP.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbTimKiemVP.setText("Tìm kiếm: ");

        btLocVP.setBackground(new java.awt.Color(93, 163, 217));
        btLocVP.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btLocVP.setForeground(new java.awt.Color(255, 255, 255));
        btLocVP.setText("Lọc");
        btLocVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLocVPActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel1.setText("Từ ngày");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("Đến ngày");

        dcTuNgay.setDateFormatString("dd-MM-yyyy");
        dcTuNgay.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        dcDenNgay.setDateFormatString("dd-MM-yyyy");
        dcDenNgay.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtNgayVP.setDateFormatString("dd-MM-yyyy");
        txtNgayVP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        cbLoai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MSSV", "Mã vi phạm" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(283, 283, 283)
                                            .addComponent(lbDSViPham))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(txtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(40, 40, 40)
                                            .addComponent(lbNgayVP)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtNgayVP, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbTimKiemVP)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCbTim, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dcTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dcDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btXoa))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btThem)
                                        .addComponent(btLocVP))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addComponent(lbTaoViPham, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDSViPham)
                .addGap(19, 19, 19)
                .addComponent(lbTaoViPham)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbMSSV)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtMSSV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayVP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNgayVP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbTimKiemVP)
                                    .addComponent(cbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCbTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dcDenNgay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(dcTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLocVP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btXoa)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(350, 309));

        btViPham.setBackground(new java.awt.Color(254, 254, 254));
        btViPham.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btViPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bx--message-error.png"))); // NOI18N
        btViPham.setText("  Vi phạm");
        btViPham.setBorder(null);
        btViPham.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btViPham.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btViPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViPhamActionPerformed(evt);
            }
        });

        btYeuCau.setBackground(new java.awt.Color(254, 254, 254));
        btYeuCau.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btYeuCau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pajamas--issue-type-requirements.png"))); // NOI18N
        btYeuCau.setText("  Yêu cầu sinh viên");
        btYeuCau.setBorder(null);
        btYeuCau.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btYeuCau.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btYeuCau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btYeuCauActionPerformed(evt);
            }
        });

        btDSSinhVien.setBackground(new java.awt.Color(254, 254, 254));
        btDSSinhVien.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btDSSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fluent--people-list-16-filled.png"))); // NOI18N
        btDSSinhVien.setText("  Quản lý sinh viên");
        btDSSinhVien.setBorder(null);
        btDSSinhVien.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btDSSinhVien.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btDSSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDSSinhVienActionPerformed(evt);
            }
        });

        lbChucNang.setBackground(new java.awt.Color(255, 255, 255));
        lbChucNang.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lbChucNang.setForeground(new java.awt.Color(83, 160, 219));
        lbChucNang.setText("Menu");

        jButton1.setBackground(new java.awt.Color(254, 254, 254));
        jButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/solar--logout-2-outline (1).png"))); // NOI18N
        jButton1.setText("  Đăng xuất");
        jButton1.setBorder(null);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setMaximumSize(new java.awt.Dimension(167, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(167, 50));
        jButton1.setName("Dangxuat"); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(167, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(254, 254, 254));
        jButton2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/material-symbols--room-preferences-outline (1).png"))); // NOI18N
        jButton2.setText("  Quản lý phòng");
        jButton2.setBorder(null);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jbtttcn.setBackground(new java.awt.Color(254, 254, 254));
        jbtttcn.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jbtttcn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fluent--person-20-filled.png"))); // NOI18N
        jbtttcn.setText("Thông tin cá nhân");
        jbtttcn.setBorder(null);
        jbtttcn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jbtttcn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtttcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtttcnActionPerformed(evt);
            }
        });

        btthongbao.setBackground(new java.awt.Color(254, 254, 254));
        btthongbao.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btthongbao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/carbon--notification-filled (3).png"))); // NOI18N
        btthongbao.setText("  Thông báo");
        btthongbao.setBorder(null);
        btthongbao.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btthongbao.setMaximumSize(new java.awt.Dimension(255, 50));
        btthongbao.setMinimumSize(new java.awt.Dimension(255, 50));
        btthongbao.setPreferredSize(new java.awt.Dimension(255, 50));
        btthongbao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthongbaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btYeuCau, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(btViPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtttcn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btDSSinhVien))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btthongbao, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbChucNang)
                .addGap(149, 149, 149))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbChucNang)
                .addGap(35, 35, 35)
                .addComponent(btthongbao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btDSSinhVien)
                .addGap(30, 30, 30)
                .addComponent(jButton2)
                .addGap(30, 30, 30)
                .addComponent(btYeuCau)
                .addGap(30, 30, 30)
                .addComponent(btViPham)
                .addGap(30, 30, 30)
                .addComponent(jbtttcn)
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 1548, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
     
        String mssv = txtMSSV.getText();
        String noidung = txtNoiDung.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String ngayvp = sdf.format(txtNgayVP.getDate());
        String manv = DangNhap.GlobalVariables.username;
        if(mssv.equals("") || noidung.equals("") || ngayvp.equals("")){
            JOptionPane.showMessageDialog(this, "Điền đầy đủ thông tin", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Connection con = QLKTX.getConnection();
        if(con == null) {
            JOptionPane.showMessageDialog(this,"Lỗi kết nối csdl","Lỗi",JOptionPane.ERROR_MESSAGE);
            return;
        }
        String sql = "{CALL THEM_VIPHAM(?,?,?,?,?,?)}";
        try{                
                CallableStatement cst = con.prepareCall(sql);
                cst.registerOutParameter(1,java.sql.Types.VARCHAR);
                cst.setString(2,manv);
                cst.setString(3,mssv);
                cst.setString(4,noidung);
                cst.setString(5,ngayvp);   
                cst.registerOutParameter(6,java.sql.Types.VARCHAR);
                cst.execute();
                
                String mavp = cst.getString(1);
                String ngaylapvp = cst.getString(6);
                DefaultTableModel model = (DefaultTableModel)tbDSViPham.getModel();
                model.addRow(new Object[]{mavp,mssv,noidung,ngayvp,ngaylapvp});
                cst.close();
                con.close();
                
        }
        catch(SQLException e){
            e.printStackTrace();
            StringBuilder errorMessage = new StringBuilder();
                    errorMessage.append("Message: ").append(e.getMessage()).append("\n");
                    JOptionPane.showMessageDialog(null, errorMessage.toString(), "Lỗi cơ sở dữ liệu", JOptionPane.ERROR_MESSAGE);
        }              
        txtMSSV.setText("");
        txtNoiDung.setText("");
        txtNgayVP.setDate(null);   
    }//GEN-LAST:event_btThemActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        int row = tbDSViPham.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this,"Chọn 1 dòng để xóa", "Lỗi",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Connection con = QLKTX.getConnection();
        if(con == null) {
            JOptionPane.showMessageDialog(this,"Lỗi kết nối csdl","Lỗi",JOptionPane.ERROR_MESSAGE);
            return;
        }
        DefaultTableModel model = (DefaultTableModel)tbDSViPham.getModel();
        String mavp = (String)model.getValueAt(row, 0);
        int ret = JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa vi phạm này","Thông báo",JOptionPane.YES_NO_OPTION);
        if(ret == JOptionPane.YES_OPTION){
            model.removeRow(row);
         String sql = "DELETE FROM PHIEUVIPHAM WHERE MAVIPHAM = ?";
         try{
             PreparedStatement pst = con.prepareStatement(sql);
             pst.setString(1,mavp);
             pst.executeUpdate();
             
             pst.close();
             con.close();
         }catch(SQLException e){
             e.printStackTrace();
         }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btLocVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLocVPActionPerformed
        String manv = DangNhap.GlobalVariables.username;
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    String loai = (String) cbLoai.getSelectedItem();
    String filterLoai = txtCbTim.getText();
    String tungay = dcTuNgay.getDate() != null ? sdf.format(dcTuNgay.getDate()) : "";
    String denngay = dcDenNgay.getDate() != null ? sdf.format(dcDenNgay.getDate()) : "";

    // Kiểm tra nếu không có điều kiện lọc nào thì tải lại dữ liệu
    if (filterLoai.isEmpty() && tungay.isEmpty() && denngay.isEmpty()) {
        loadData();
        return;
    }

    Connection con = QLKTX.getConnection();
    if (con == null) {
        JOptionPane.showMessageDialog(this, "Lỗi kết nối csdl", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Tạo 1 table mới
    DefaultTableModel table = new DefaultTableModel();
    // Gán cho table cột
    String title[] = {"Mã vi phạm", "MSSV", "Nội dung", "Ngày vi phạm", "Ngày lập vi phạm"};
    table.setColumnIdentifiers(title);

    try {
        StringBuilder sql = new StringBuilder("SELECT * FROM PHIEUVIPHAM P JOIN CUTRU C ON P.MSSV = C.MSSV"
                + " JOIN PHONG ON C.MAPHONG = PHONG.MAPHONG"
                + " JOIN TOA T ON PHONG.MATOA = T.MATOA"
                + " WHERE T.MATRUONGTOA = ?");

        if (!filterLoai.isEmpty()) {
            if ("MSSV".equals(loai)) {
                sql.append(" AND P.MSSV = ?");
            } else if ("Mã vi phạm".equals(loai)) {
                sql.append(" AND P.MAVIPHAM = ?");
            }
        }

        if (!tungay.isEmpty() && denngay.isEmpty()) {
            sql.append(" AND P.NGAYLAPVP >= TO_DATE(?, 'DD-MM-YYYY')");
        } else if (tungay.isEmpty() && !denngay.isEmpty()) {
            sql.append(" AND P.NGAYLAPVP<= TO_DATE(?, 'DD-MM-YYYY')");
        } else if (!tungay.isEmpty() && !denngay.isEmpty()) {
            sql.append(" AND P.NGAYLAPVPBETWEEN TO_DATE(?, 'DD-MM-YYYY') AND TO_DATE(?, 'DD-MM-YYYY')");
        }

        PreparedStatement pst = con.prepareStatement(sql.toString());
        pst.setString(1, manv);
        int index = 2;

        if (!filterLoai.isEmpty()) {
            pst.setString(index++, filterLoai);
        }

        if (!tungay.isEmpty() && denngay.isEmpty()) {
            pst.setString(index++, tungay);
        } else if (tungay.isEmpty() && !denngay.isEmpty()) {
            pst.setString(index++, denngay);
        } else if (!tungay.isEmpty() && !denngay.isEmpty()) {
            pst.setString(index++, tungay);
            pst.setString(index++, denngay);
        }
        ResultSet rs = pst.executeQuery();
        while (rs.next()) {
            String maVP = rs.getString("MAVIPHAM");
            String mssv = rs.getString("MSSV");
            String noiDung = rs.getString("NOIDUNG");
            Date ngayViPham = rs.getDate("NGAYVIPHAM");
            Date ngayLapVP = rs.getDate("NGAYLAPVP");
            String ngayvp = sdf.format(ngayViPham);
            String ngaylapvp = sdf.format(ngayLapVP);

            table.addRow(new Object[]{maVP, mssv, noiDung, ngayvp, ngaylapvp});
        }
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
                for (int i = 0; i < tbDSViPham.getColumnCount(); i++) {
                    tbDSViPham.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
                }
        // Gán dữ liệu mới vào bảng
        tbDSViPham.setModel(table);

        rs.close();
        pst.close();
        con.close();
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi trong quá trình truy vấn cơ sở dữ liệu", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btLocVPActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TrangChuNV d = new TrangChuNV();
        d.setVisible(true);
    }//GEN-LAST:event_btBackActionPerformed

    private void btViPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViPhamActionPerformed
        QLViPham qlvp = new QLViPham();
        qlvp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btViPhamActionPerformed

    private void btYeuCauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btYeuCauActionPerformed
        QLYeuCau qlyc = new QLYeuCau();
        qlyc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btYeuCauActionPerformed

    private void btDSSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDSSinhVienActionPerformed
        DSSinhVien dssv = new DSSinhVien(this);
        dssv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btDSSinhVienActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int ret = JOptionPane.showConfirmDialog(this,"Bạn có muốn đăng xuất?","Thông báo",JOptionPane.YES_NO_OPTION);
        if(ret == JOptionPane.YES_OPTION){
            DangNhap dn = new DangNhap();
            dn.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        QLPhong qlphong = new QLPhong(this);
        qlphong.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtttcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtttcnActionPerformed
        ThongTinCaNhanNV ttcn = new ThongTinCaNhanNV();
        ttcn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtttcnActionPerformed

    private void btthongbaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthongbaoActionPerformed
        TrangChuNV tcnv = new TrangChuNV(this);
        tcnv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btthongbaoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {              
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new QLViPham().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btthongbao;
    private javax.swing.JComboBox<String> cbLoai;
    private com.toedter.calendar.JDateChooser dcDenNgay;
    private com.toedter.calendar.JDateChooser dcTuNgay;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtttcn;
    private javax.swing.JLabel lbWebDev;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JTable tbDSViPham;
    private javax.swing.JTextField txtCbTim;
    private javax.swing.JTextField txtMSSV;
    private com.toedter.calendar.JDateChooser txtNgayVP;
    private javax.swing.JTextField txtNoiDung;
    // End of variables declaration//GEN-END:variables
}
