/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SinhVien;

import static com.mycompany.qlktx.QLKTX.*;
import com.mycompany.qlktx.DangNhap;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class HoaDonSV extends javax.swing.JFrame {
    String mssv = DangNhap.GlobalVariables.username;
    //String mssv = "00520001";
    
    private DefaultTableModel tb;
    /**
     * Creates new form HoaDonSV
     */
    public HoaDonSV() {
        initComponents();
        btBack.setBorderPainted(false); 
        btBack.setContentAreaFilled(false);
        
        thietlapManHinh();
        layDSHoaDon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        lbAnhWebDev = new javax.swing.JLabel();
        btBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbTTHD = new javax.swing.JLabel();
        lbBL = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbHD = new javax.swing.JTable();
        btTimKiem = new javax.swing.JButton();
        lbGhiChuTTHD = new javax.swing.JLabel();
        ckbThanhToan = new javax.swing.JCheckBox();
        txtMaHD = new javax.swing.JTextField();
        cbLoaiHD = new javax.swing.JComboBox<>();
        lbBL1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 80));

        lbAnhWebDev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.jpg"))); // NOI18N

        btBack.setBackground(new java.awt.Color(254, 254, 254));
        btBack.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btBack.setForeground(new java.awt.Color(255, 255, 255));
        btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Back.png"))); // NOI18N
        btBack.setBorder(null);
        btBack.setBorderPainted(false);
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btBack)
                .addGap(253, 253, 253)
                .addComponent(lbAnhWebDev, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btBack)
                .addGap(21, 21, 21))
            .addComponent(lbAnhWebDev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 80));

        lbTTHD.setBackground(new java.awt.Color(255, 255, 255));
        lbTTHD.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lbTTHD.setForeground(new java.awt.Color(83, 160, 219));
        lbTTHD.setText("Thông Tin Hoá Đơn");

        lbBL.setBackground(new java.awt.Color(255, 255, 255));
        lbBL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbBL.setText("Mã hóa đơn:");

        tbHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Loại hóa đơn", "Giá Tiền", "Ngày lập hóa đơn", "Hạn thanh toán", "Ngày thanh toán"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tbHD);

        btTimKiem.setBackground(new java.awt.Color(93, 163, 217));
        btTimKiem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btTimKiem.setText("Tìm Kiếm");
        btTimKiem.setActionCommand("");
        btTimKiem.setBorder(null);
        btTimKiem.setBorderPainted(false);
        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });

        lbGhiChuTTHD.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbGhiChuTTHD.setText("*Hóa đơn có ngày thanh toán để trống là hóa đơn chưa thanh toán.");

        ckbThanhToan.setBackground(new java.awt.Color(255, 255, 255));
        ckbThanhToan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ckbThanhToan.setText("Chưa thanh toán");

        txtMaHD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        cbLoaiHD.setBackground(new java.awt.Color(254, 254, 254));
        cbLoaiHD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbLoaiHD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbBL1.setBackground(new java.awt.Color(255, 255, 255));
        lbBL1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbBL1.setText("Loại hóa đơn:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbBL, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                        .addComponent(txtMaHD))
                                    .addGap(73, 73, 73)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cbLoaiHD, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ckbThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(60, 60, 60)
                                    .addComponent(btTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbGhiChuTTHD)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(lbTTHD)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbTTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBL)
                    .addComponent(lbBL1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(txtMaHD, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addComponent(cbLoaiHD)
                        .addComponent(ckbThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(lbGhiChuTTHD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        this.dispose();
        TrangChuSV trangchuSV = new TrangChuSV();
        trangchuSV.setVisible(true);
    }//GEN-LAST:event_btBackActionPerformed

    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
        // TODO add your handling code here:
        layDSHoaDon();
    }//GEN-LAST:event_btTimKiemActionPerformed

    public void thietlapManHinh() {
        tb = new DefaultTableModel();
        String tieuDe[] = {"Mã hóa đơn", "Loại hóa đơn", "Mã Phòng", "Giá tiền", "Ngày lập hóa đơn", "Hạn thanh toán", "Ngày thanh toán"};
        tb.setColumnIdentifiers(tieuDe);
        tbHD.setModel(tb);
        setVisible(true);
        
        String[] itemsFilterLoaiHD = {"Default", "Sua chua", "Tien dien", "Tien nuoc", "Tien phong"};
        
        DefaultComboBoxModel<String> insertLoaiHD = new DefaultComboBoxModel<>(itemsFilterLoaiHD);
        cbLoaiHD.setModel(insertLoaiHD);

    }
    
    public void layDSHoaDon() {
        String maHD = txtMaHD.getText();
        String loaiHDFilter = (String) cbLoaiHD.getSelectedItem();
        boolean ckThanhToan = ckbThanhToan.isSelected();
                
        Connection con = getConnection();
        if (con == null) {
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu", "Error", JOptionPane.ERROR_MESSAGE);
        }
            
        try {           
            StringBuilder sql = new StringBuilder("SELECT MAHOADON, H.MAPHONG, SOTIEN, LOAIHOADON, NGAYLAPHOADON, HANTHANHTOAN, NGAYTHANHTOAN "
                    + "FROM HOADON H RIGHT JOIN (SELECT * FROM CUTRU WHERE MSSV = ?) C ON H.MAPHONG = C.MAPHONG WHERE H.MSSV = ? OR H.MSSV IS NULL");
            if (!maHD.isEmpty()) {
                sql.append(" AND MAHOADON = ?");
            }
            if (!"Default".equals(loaiHDFilter)) {
                sql.append(" AND LOAIHOADON = ?");
            }
            if(ckThanhToan) {
                sql.append(" AND NGAYTHANHTOAN IS NULL");
            }
            sql.append(" ORDER BY MAHOADON");

            PreparedStatement pstmt = con.prepareStatement(sql.toString());
            pstmt.setString(1, mssv);
            pstmt.setString(2, mssv);
            
            int parameterIndex = 3;
            if (!maHD.isEmpty()) {
                pstmt.setString(parameterIndex++, maHD);
            }
            if (!"Default".equals(loaiHDFilter)) {
                pstmt.setString(parameterIndex++, loaiHDFilter);
            }
            ResultSet rs = pstmt.executeQuery();
            
            tb.setRowCount(0); // Clear table
            while (rs.next()) {
                String maHoaDon = rs.getString("MAHOADON");
                String maP = rs.getString("MAPHONG");
                String loaiHD = rs.getString("LOAIHOADON");
                String tienHD = rs.getString("SOTIEN");
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                Date ngaylap = rs.getDate("NGAYLAPHOADON");
                String ngLHD = sdf.format(ngaylap);
                String hanHD = sdf.format(rs.getDate("HANTHANHTOAN"));
                String ngTT = "";
                if(rs.getString("NGAYTHANHTOAN") != null)
                    ngTT = convertDateFormat(rs.getString("NGAYTHANHTOAN"));
                tb.addRow(new Object[]{maHoaDon, loaiHD, maP, tienHD, ngLHD, hanHD, ngTT});
            }
            rs.close();
            pstmt.close();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi trong quá trình truy vấn cơ sở dữ liệu", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JComboBox<String> cbLoaiHD;
    private javax.swing.JCheckBox ckbThanhToan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbAnhWebDev;
    private javax.swing.JLabel lbBL;
    private javax.swing.JLabel lbBL1;
    private javax.swing.JLabel lbGhiChuTTHD;
    private javax.swing.JLabel lbTTHD;
    private javax.swing.JTable tbHD;
    private javax.swing.JTextField txtMaHD;
    // End of variables declaration//GEN-END:variables
}
