/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NhanVienKeToanMo;

import static com.mycompany.qlktx.QLKTX.*;
import com.mycompany.qlktx.DangNhap;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ThongBaoKT extends javax.swing.JFrame {
    //String maKT = GUI.DangNhap.GlobalVariables.username;
    String maKT = "NV11";
    /**
     * Creates new form ThongBao
     */
    private DefaultTableModel tbThongBao;
    public ThongBaoKT() {
        initComponents();
        setSize(800, 600);
        thietlapManHinh();
        layDSThongBao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbAnhWebDev = new javax.swing.JLabel();
        btBack = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        javax.swing.JLabel lbChucNang = new javax.swing.JLabel();
        btThongBao = new javax.swing.JButton();
        btTraCuuPhong = new javax.swing.JButton();
        btHoaDon = new javax.swing.JButton();
        btDangXuat = new javax.swing.JButton();
        btThongKe = new javax.swing.JButton();
        btThongTinCN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbTB = new javax.swing.JLabel();
        lbTK = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblThongBao = new javax.swing.JTable();
        btTimKiem = new javax.swing.JButton();
        txtThongBao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(1512, 1020));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 80));

        lbAnhWebDev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAnhWebDev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.jpg"))); // NOI18N

        btBack.setBackground(new java.awt.Color(254, 254, 254));
        btBack.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btBack.setForeground(new java.awt.Color(255, 255, 255));
        btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Back.png"))); // NOI18N
        btBack.setBorder(null);
        btBack.setBorderPainted(false);
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btBack)
                .addGap(18, 18, 18)
                .addComponent(lbAnhWebDev, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1603, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btBack)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAnhWebDev, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1954, -1));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.setPreferredSize(new java.awt.Dimension(350, 309));

        lbChucNang.setBackground(new java.awt.Color(255, 255, 255));
        lbChucNang.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lbChucNang.setForeground(new java.awt.Color(83, 160, 219));
        lbChucNang.setText("Menu");

        btThongBao.setBackground(new java.awt.Color(254, 254, 254));
        btThongBao.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btThongBao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ThongBao.png"))); // NOI18N
        btThongBao.setText("Thông báo");
        btThongBao.setBorder(null);
        btThongBao.setBorderPainted(false);
        btThongBao.setHideActionText(true);
        btThongBao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btThongBao.setIconTextGap(10);
        btThongBao.setOpaque(true);
        btThongBao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThongBaoActionPerformed(evt);
            }
        });

        btTraCuuPhong.setBackground(new java.awt.Color(254, 254, 254));
        btTraCuuPhong.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btTraCuuPhong.setForeground(new java.awt.Color(153, 153, 153));
        btTraCuuPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TraCuu 50x50.png"))); // NOI18N
        btTraCuuPhong.setText("Tra cứu phòng");
        btTraCuuPhong.setBorder(null);
        btTraCuuPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btTraCuuPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btTraCuuPhong.setIconTextGap(10);
        btTraCuuPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTraCuuPhongActionPerformed(evt);
            }
        });

        btHoaDon.setBackground(new java.awt.Color(254, 254, 254));
        btHoaDon.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btHoaDon.setForeground(new java.awt.Color(153, 153, 153));
        btHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/HoaDon.png"))); // NOI18N
        btHoaDon.setText("Hóa đơn");
        btHoaDon.setBorder(null);
        btHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btHoaDon.setIconTextGap(10);
        btHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHoaDonActionPerformed(evt);
            }
        });

        btDangXuat.setBackground(new java.awt.Color(254, 254, 254));
        btDangXuat.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btDangXuat.setForeground(new java.awt.Color(153, 153, 153));
        btDangXuat.setText("Đăng xuất");
        btDangXuat.setBorder(null);
        btDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDangXuatActionPerformed(evt);
            }
        });

        btThongKe.setBackground(new java.awt.Color(254, 254, 254));
        btThongKe.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btThongKe.setForeground(new java.awt.Color(153, 153, 153));
        btThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CongDong.png"))); // NOI18N
        btThongKe.setText("Thống kê");
        btThongKe.setBorder(null);
        btThongKe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btThongKe.setIconTextGap(10);
        btThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThongKeActionPerformed(evt);
            }
        });

        btThongTinCN.setBackground(new java.awt.Color(254, 254, 254));
        btThongTinCN.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btThongTinCN.setForeground(new java.awt.Color(153, 153, 153));
        btThongTinCN.setText("Thông tin cá nhân");
        btThongTinCN.setBorder(null);
        btThongTinCN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btThongTinCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThongTinCNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addComponent(btThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(lbChucNang)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btThongTinCN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btTraCuuPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbChucNang)
                .addGap(18, 18, 18)
                .addComponent(btThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btTraCuuPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btThongTinCN, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(423, 423, 423))
        );

        jPanel3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, 380, 950));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 80));

        lbTB.setBackground(new java.awt.Color(255, 255, 255));
        lbTB.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbTB.setForeground(new java.awt.Color(83, 160, 219));
        lbTB.setText("Thông Báo");

        lbTK.setBackground(new java.awt.Color(255, 255, 255));
        lbTK.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbTK.setText("Tìm kiếm nội dung:");

        tblThongBao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thông báo", "Nội dung"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblThongBao);

        btTimKiem.setBackground(new java.awt.Color(93, 163, 217));
        btTimKiem.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btTimKiem.setText("Tìm Kiếm");
        btTimKiem.setActionCommand("");
        btTimKiem.setBorder(null);
        btTimKiem.setBorderPainted(false);
        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });

        txtThongBao.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtThongBao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(466, 466, 466))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(439, 439, 439)
                        .addComponent(lbTB))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lbTK)
                        .addGap(59, 59, 59)
                        .addComponent(txtThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbTB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTK, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 1140, 940));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        this.dispose();
        TrangChuKT trangchuKT = new TrangChuKT();
        trangchuKT.setVisible(true);
    }//GEN-LAST:event_btBackActionPerformed

    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
        layDSThongBao();
    }//GEN-LAST:event_btTimKiemActionPerformed

    private void btThongBaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThongBaoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TrangChuKT tcKT = new TrangChuKT();
        tcKT.setVisible(true);
    }//GEN-LAST:event_btThongBaoActionPerformed

    private void btTraCuuPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTraCuuPhongActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TraCuuPhongKT tcpKT = new TraCuuPhongKT();
        tcpKT.setVisible(true);
    }//GEN-LAST:event_btTraCuuPhongActionPerformed

    private void btHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHoaDonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HoaDonKT hoadonKT = new HoaDonKT();
        hoadonKT.setVisible(true);
    }//GEN-LAST:event_btHoaDonActionPerformed

    private void btDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangXuatActionPerformed
        int ret = JOptionPane.showConfirmDialog(null, "Bạn có muốn đăng xuất", "Đăng xuất", JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
            this.dispose();
            DangNhap dangnhap = new DangNhap();
            dangnhap.setVisible(true);
        }
    }//GEN-LAST:event_btDangXuatActionPerformed

    private void btThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThongKeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ThongKeKT thongkeKT = new ThongKeKT();
        thongkeKT.setVisible(true);
    }//GEN-LAST:event_btThongKeActionPerformed

    private void btThongTinCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThongTinCNActionPerformed
        this.setVisible(false);
        TrangChuKT thongtinKT = new TrangChuKT();
        thongtinKT.setVisible(true);
    }//GEN-LAST:event_btThongTinCNActionPerformed
    
    private void thietlapManHinh() {
        tbThongBao = new DefaultTableModel();
        String tieuDe1[] = {"Mã thông báo", "Nội dung"};
        tbThongBao.setColumnIdentifiers(tieuDe1);
        tblThongBao.setModel(tbThongBao);
        setVisible(true);
    }

    private void layDSThongBao() {
        String ndTimKiem = txtThongBao.getText();
        
        Connection con = getConnection();
        if (con == null) {
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu", "Error", JOptionPane.ERROR_MESSAGE);
        }
            
        try {           
            StringBuilder sql = new StringBuilder("SELECT MATHONGBAO, NOIDUNG FROM THONGBAO WHERE MANGUOINHAN IS NULL");
            if (!ndTimKiem.isEmpty()) {
                ndTimKiem = "%" + ndTimKiem + "%";
                sql.append(" AND NOIDUNG LIKE ?");
            }
            sql.append(" ORDER BY MATHONGBAO");
                       
            
            PreparedStatement pstmt = con.prepareStatement(sql.toString());
            if (!ndTimKiem.isEmpty()) {
                pstmt.setString(1, ndTimKiem);
            }
            ResultSet rs = pstmt.executeQuery();
            
            tbThongBao.setRowCount(0); // Clear table
            while (rs.next()) {
                String maTB = rs.getString("MATHONGBAO");
                String ndTB = rs.getString("NOIDUNG");
                tbThongBao.addRow(new Object[]{maTB, ndTB});
            }
            
            rs.close();
            pstmt.close();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi trong quá trình truy vấn cơ sở dữ liệu1", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btDangXuat;
    private javax.swing.JButton btHoaDon;
    private javax.swing.JButton btThongBao;
    private javax.swing.JButton btThongKe;
    private javax.swing.JButton btThongTinCN;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btTraCuuPhong;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbAnhWebDev;
    private javax.swing.JLabel lbTB;
    private javax.swing.JLabel lbTK;
    private javax.swing.JTable tblThongBao;
    private javax.swing.JTextField txtThongBao;
    // End of variables declaration//GEN-END:variables

    
}
