/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NhanVienKeToanMo;

import static com.mycompany.qlktx.QLKTX.*;
import com.mycompany.qlktx.DangNhap;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class TraCuuPhongKT extends javax.swing.JFrame {
    String maKT = DangNhap.GlobalVariables.username;
    //String maKT = "NV11";
    
    private DefaultTableModel tb;

    public TraCuuPhongKT() {
        initComponents();
        
        thietlapManHinh();
        layDSPhong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lbTTHD1 = new javax.swing.JLabel();
        lbBL1 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbTTP = new javax.swing.JTable();
        btTK = new javax.swing.JButton();
        txtMaPhong = new javax.swing.JTextField();
        cbLoaiPhong = new javax.swing.JComboBox<>();
        ckbConPhong = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cbLoaiToa = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 80));

        lbTTHD1.setBackground(new java.awt.Color(255, 255, 255));
        lbTTHD1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbTTHD1.setForeground(new java.awt.Color(83, 160, 219));
        lbTTHD1.setText("Tra cứu thông tin phòng");

        lbBL1.setBackground(new java.awt.Color(255, 255, 255));
        lbBL1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbBL1.setForeground(new java.awt.Color(51, 51, 51));
        lbBL1.setText("Mã phòng:");

        tbTTP.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tbTTP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng", "Loại tòa", "Loại phòng", "Giá tiền", "Tình trạng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbTTP.setRowHeight(40);
        jScrollPane7.setViewportView(tbTTP);

        btTK.setBackground(new java.awt.Color(93, 163, 217));
        btTK.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btTK.setForeground(new java.awt.Color(255, 255, 255));
        btTK.setText("Tìm Kiếm");
        btTK.setActionCommand("");
        btTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTKActionPerformed(evt);
            }
        });

        cbLoaiPhong.setBackground(new java.awt.Color(254, 254, 254));
        cbLoaiPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbLoaiPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ckbConPhong.setBackground(new java.awt.Color(254, 254, 254));
        ckbConPhong.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ckbConPhong.setText("Phòng còn trống");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Loại phòng");

        cbLoaiToa.setBackground(new java.awt.Color(254, 254, 254));
        cbLoaiToa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbLoaiToa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Loại tòa");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(114, 114, 114)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(108, 108, 108)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btTK, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ckbConPhong)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbTTHD1)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbTTHD1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(ckbConPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btTK)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbBL1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbLoaiToa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTKActionPerformed
        // TODO add your handling code here:
        layDSPhong();
    }//GEN-LAST:event_btTKActionPerformed

    public void thietlapManHinh() {
        tb = new DefaultTableModel();
        String tieuDe[] = {"Mã phòng", "Loại tòa","Loại phòng", "Giá tiền", "Tình trạng"};
        tb.setColumnIdentifiers(tieuDe);
        tbTTP.setModel(tb);
        setVisible(true);
        
        String[] itemsFilterLoaiP = {"Default", "2", "4", "6", "8"};
        String[] itemsFilterLoaiT = {"Default", "Nam", "Nu"};
        
        DefaultComboBoxModel<String> insertLoaiP = new DefaultComboBoxModel<>(itemsFilterLoaiP);
        cbLoaiPhong.setModel(insertLoaiP);
        
        DefaultComboBoxModel<String> insertLoaiT = new DefaultComboBoxModel<>(itemsFilterLoaiT);
        cbLoaiToa.setModel(insertLoaiT);
    }
    
    
    public void layDSPhong() {
        String maPhong = txtMaPhong.getText().trim();
        String loaiPFilter = (String) cbLoaiPhong.getSelectedItem();
        String loaiTFilter = (String) cbLoaiToa.getSelectedItem();
        String lToa = "";
        if(loaiTFilter.equals("Nam")) lToa = "1";
        if(loaiTFilter.equals("Nu")) lToa = "0";
        boolean ckConPhong = ckbConPhong.isSelected();
                
        Connection con = getConnection();
        if (con == null) {
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu", "Error", JOptionPane.ERROR_MESSAGE);
        }
            
        try {           
            StringBuilder sql = new StringBuilder("SELECT MAPHONG, LOAITOA, LOAIPHONG, GIATIEN, SISO FROM PHONG JOIN TOA ON PHONG.MATOA = TOA.MATOA");
            int index = 0;
            
            if (!maPhong.isEmpty()) {
                if(index == 0) {
                    sql.append(" WHERE");
                    index++;
                }
                maPhong = "%" + maPhong + "%";
                sql.append(" MAPHONG LIKE ?");
            }
            if (!"Default".equals(loaiPFilter)) {
                if(index == 0) {
                    sql.append(" WHERE");
                    index++;
                } else sql.append(" AND");
                sql.append(" LOAIPHONG = ?");
            }
            if (!"Default".equals(loaiTFilter)) {
                if(index == 0) {
                    sql.append(" WHERE");
                    index++;
                } else sql.append(" AND");
                sql.append(" LOAITOA = ?");
            }
            if(ckConPhong) {
                if(index == 0) {
                    sql.append(" WHERE");
                    index++;
                } else sql.append(" AND");
                sql.append(" SISO < LOAIPHONG");
            }
            sql.append(" ORDER BY MAPHONG");

            PreparedStatement pstmt = con.prepareStatement(sql.toString());
            
            int parameterIndex = 1;
            if (!maPhong.isEmpty()) {
                pstmt.setString(parameterIndex++, maPhong);
            }
            if (!"Default".equals(loaiPFilter)) {
                pstmt.setString(parameterIndex++, loaiPFilter);
            }
            if (!"Default".equals(loaiTFilter)) {
                pstmt.setString(parameterIndex++, lToa);
            }
            ResultSet rs = pstmt.executeQuery();
            
            tb.setRowCount(0); // Clear table
            while (rs.next()) {
                String maP = rs.getString("MAPHONG");
                String loaiT = rs.getString("LOAITOA");
                String txtLToa;
                if(loaiT.equals("0")) txtLToa = "Nữ";
                else txtLToa = "Nam";
                String loaiP = rs.getString("LOAIPHONG");
                String tienP = rs.getString("GIATIEN");
                String ttP = rs.getString("SISO") + "/" + loaiP;
                tb.addRow(new Object[]{maP, txtLToa, loaiP, tienP, ttP});
            }
            rs.close();
            pstmt.close();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi trong quá trình truy vấn cơ sở dữ liệu", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTK;
    private javax.swing.JComboBox<String> cbLoaiPhong;
    private javax.swing.JComboBox<String> cbLoaiToa;
    private javax.swing.JCheckBox ckbConPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lbBL1;
    private javax.swing.JLabel lbTTHD1;
    private javax.swing.JTable tbTTP;
    private javax.swing.JTextField txtMaPhong;
    // End of variables declaration//GEN-END:variables
}
