/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SinhVienMoi;

import com.mycompany.qlktx.CapNhatCuTru;
import com.mycompany.qlktx.DSSinhVien;
import static com.mycompany.qlktx.QLKTX.*;
import com.mycompany.qlktx.DangNhap;
import com.mycompany.qlktx.QLThongBao;
import com.mycompany.qlktx.QLViPham;
import com.mycompany.qlktx.QLYeuCau;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


public class HoaDonSV extends javax.swing.JFrame {
    String mssv = DangNhap.GlobalVariables.username;
    //String mssv = "00520001";
    
    private DefaultTableModel tb;
    /**
     * Creates new form HoaDonSV
     */
    public HoaDonSV() {
        initComponents();
        btBack.setBorderPainted(false); 
        btBack.setContentAreaFilled(false);
        
        thietlapManHinh();
        layDSHoaDon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        lbAnhWebDev = new javax.swing.JLabel();
        btBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbTTHD = new javax.swing.JLabel();
        lbBL = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbHD = new javax.swing.JTable();
        btTimKiem = new javax.swing.JButton();
        lbGhiChuTTHD = new javax.swing.JLabel();
        ckbThanhToan = new javax.swing.JCheckBox();
        txtMaHD = new javax.swing.JTextField();
        cbLoaiHD = new javax.swing.JComboBox<>();
        lbBL1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        javax.swing.JLabel lbChucNang1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        btThongBao = new javax.swing.JButton();
        btTB = new javax.swing.JButton();
        btYeuCau = new javax.swing.JButton();
        btYC = new javax.swing.JButton();
        btViPham = new javax.swing.JButton();
        btVP = new javax.swing.JButton();
        btCuTru = new javax.swing.JButton();
        btCT = new javax.swing.JButton();
        btHoaDon = new javax.swing.JButton();
        btHD = new javax.swing.JButton();
        btHoatDong = new javax.swing.JButton();
        btHoatDong2 = new javax.swing.JButton();
        btTraCuuPhong = new javax.swing.JButton();
        btTCP = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 80));

        lbAnhWebDev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.jpg"))); // NOI18N

        btBack.setBackground(new java.awt.Color(254, 254, 254));
        btBack.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btBack.setForeground(new java.awt.Color(255, 255, 255));
        btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Back.png"))); // NOI18N
        btBack.setBorder(null);
        btBack.setBorderPainted(false);
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btBack)
                .addGap(34, 34, 34)
                .addComponent(lbAnhWebDev, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1335, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbAnhWebDev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(btBack)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1632, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 3, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 80));

        lbTTHD.setBackground(new java.awt.Color(255, 255, 255));
        lbTTHD.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbTTHD.setForeground(new java.awt.Color(83, 160, 219));
        lbTTHD.setText("Thông Tin Hoá Đơn");

        lbBL.setBackground(new java.awt.Color(255, 255, 255));
        lbBL.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbBL.setForeground(new java.awt.Color(86, 86, 86));
        lbBL.setText("Mã hóa đơn:");

        tbHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Loại hóa đơn", "Giá Tiền", "Ngày lập hóa đơn", "Hạn thanh toán", "Ngày thanh toán"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tbHD);

        btTimKiem.setBackground(new java.awt.Color(93, 163, 217));
        btTimKiem.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btTimKiem.setText("Tìm Kiếm");
        btTimKiem.setActionCommand("");
        btTimKiem.setBorder(null);
        btTimKiem.setBorderPainted(false);
        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });

        lbGhiChuTTHD.setBackground(new java.awt.Color(86, 86, 86));
        lbGhiChuTTHD.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbGhiChuTTHD.setForeground(new java.awt.Color(86, 86, 86));
        lbGhiChuTTHD.setText("*Hóa đơn có ngày thanh toán để trống là hóa đơn chưa thanh toán.");

        ckbThanhToan.setBackground(new java.awt.Color(255, 255, 255));
        ckbThanhToan.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ckbThanhToan.setForeground(new java.awt.Color(86, 86, 86));
        ckbThanhToan.setText("Chưa thanh toán");
        ckbThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbThanhToanActionPerformed(evt);
            }
        });

        txtMaHD.setBackground(new java.awt.Color(240, 240, 240));
        txtMaHD.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtMaHD.setForeground(new java.awt.Color(86, 86, 86));

        cbLoaiHD.setBackground(new java.awt.Color(254, 254, 254));
        cbLoaiHD.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cbLoaiHD.setForeground(new java.awt.Color(86, 86, 86));
        cbLoaiHD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbBL1.setBackground(new java.awt.Color(255, 255, 255));
        lbBL1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbBL1.setForeground(new java.awt.Color(86, 86, 86));
        lbBL1.setText("Loại hóa đơn:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbBL, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(157, 157, 157))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(cbLoaiHD, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(114, 114, 114)))
                                .addComponent(ckbThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(btTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbGhiChuTTHD)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(lbTTHD)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbTTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBL)
                    .addComponent(lbBL1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLoaiHD)
                    .addComponent(ckbThanhToan)
                    .addComponent(btTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbGhiChuTTHD)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 1234, 959));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(350, 309));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbChucNang1.setBackground(new java.awt.Color(255, 255, 255));
        lbChucNang1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lbChucNang1.setForeground(new java.awt.Color(83, 160, 219));
        lbChucNang1.setText("Menu");
        jPanel8.add(lbChucNang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 25, -1, -1));

        jButton4.setBackground(new java.awt.Color(254, 254, 254));
        jButton4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/solar--logout-2-outline (1).png"))); // NOI18N
        jButton4.setText("  Đăng xuất");
        jButton4.setBorder(null);
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton4.setMaximumSize(new java.awt.Dimension(167, 50));
        jButton4.setMinimumSize(new java.awt.Dimension(167, 50));
        jButton4.setName("Dangxuat"); // NOI18N
        jButton4.setPreferredSize(new java.awt.Dimension(167, 50));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 200, 50));

        btThongBao.setBackground(new java.awt.Color(254, 254, 254));
        btThongBao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ThongBao.png"))); // NOI18N
        btThongBao.setBorder(null);
        btThongBao.setOpaque(true);
        btThongBao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThongBaoActionPerformed(evt);
            }
        });
        jPanel8.add(btThongBao, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 95, 62, 64));

        btTB.setBackground(new java.awt.Color(254, 254, 254));
        btTB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btTB.setText("Thông báo");
        btTB.setBorder(null);
        btTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTBActionPerformed(evt);
            }
        });
        jPanel8.add(btTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 111, 131, -1));

        btYeuCau.setBackground(new java.awt.Color(254, 254, 254));
        btYeuCau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/YeuCau.png"))); // NOI18N
        btYeuCau.setBorder(null);
        btYeuCau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btYeuCauActionPerformed(evt);
            }
        });
        jPanel8.add(btYeuCau, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 165, 55, 58));

        btYC.setBackground(new java.awt.Color(254, 254, 254));
        btYC.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btYC.setText("Yêu cầu");
        btYC.setBorder(null);
        btYC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btYCActionPerformed(evt);
            }
        });
        jPanel8.add(btYC, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 179, 103, -1));

        btViPham.setBackground(new java.awt.Color(254, 254, 254));
        btViPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ViPham.png"))); // NOI18N
        btViPham.setBorder(null);
        btViPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViPhamActionPerformed(evt);
            }
        });
        jPanel8.add(btViPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 229, 63, 62));

        btVP.setBackground(new java.awt.Color(254, 254, 254));
        btVP.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btVP.setText("Vi phạm");
        btVP.setBorder(null);
        btVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVPActionPerformed(evt);
            }
        });
        jPanel8.add(btVP, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 246, 100, -1));

        btCuTru.setBackground(new java.awt.Color(254, 254, 254));
        btCuTru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CuTru.png"))); // NOI18N
        btCuTru.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btCuTru.setOpaque(true);
        btCuTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCuTruActionPerformed(evt);
            }
        });
        jPanel8.add(btCuTru, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 297, 62, 64));

        btCT.setBackground(new java.awt.Color(254, 254, 254));
        btCT.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btCT.setText("Cư trú");
        btCT.setBorder(null);
        btCT.setOpaque(true);
        btCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCTActionPerformed(evt);
            }
        });
        jPanel8.add(btCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 317, 84, -1));

        btHoaDon.setBackground(new java.awt.Color(254, 254, 254));
        btHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/HoaDon.png"))); // NOI18N
        btHoaDon.setBorder(null);
        btHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHoaDonActionPerformed(evt);
            }
        });
        jPanel8.add(btHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 367, 60, 60));

        btHD.setBackground(new java.awt.Color(254, 254, 254));
        btHD.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btHD.setForeground(new java.awt.Color(86, 86, 86));
        btHD.setText("Hóa đơn");
        btHD.setBorder(null);
        btHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHDActionPerformed(evt);
            }
        });
        jPanel8.add(btHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 383, -1, -1));

        btHoatDong.setBackground(new java.awt.Color(254, 254, 254));
        btHoatDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CongDong.png"))); // NOI18N
        btHoatDong.setBorder(null);
        btHoatDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHoatDongActionPerformed(evt);
            }
        });
        jPanel8.add(btHoatDong, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 433, 68, 52));

        btHoatDong2.setBackground(new java.awt.Color(254, 254, 254));
        btHoatDong2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btHoatDong2.setText("Hoạt động");
        btHoatDong2.setBorder(null);
        btHoatDong2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHoatDong2ActionPerformed(evt);
            }
        });
        jPanel8.add(btHoatDong2, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 444, -1, -1));

        btTraCuuPhong.setBackground(new java.awt.Color(254, 254, 254));
        btTraCuuPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TraCuu 50x50.png"))); // NOI18N
        btTraCuuPhong.setBorder(null);
        btTraCuuPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTraCuuPhongActionPerformed(evt);
            }
        });
        jPanel8.add(btTraCuuPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 503, 58, -1));

        btTCP.setBackground(new java.awt.Color(254, 254, 254));
        btTCP.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btTCP.setText("Tra cứu phòng");
        btTCP.setBorder(null);
        btTCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTCPActionPerformed(evt);
            }
        });
        jPanel8.add(btTCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 511, -1, -1));

        jButton3.setBackground(new java.awt.Color(254, 254, 254));
        jButton3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fluent--person-20-filled.png"))); // NOI18N
        jButton3.setText("Thông tin cá nhân");
        jButton3.setBorder(null);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 380, 959));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        this.dispose();
        TrangChuSV trangchuSV = new TrangChuSV();
        trangchuSV.setVisible(true);
    }//GEN-LAST:event_btBackActionPerformed

    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
        // TODO add your handling code here:
        layDSHoaDon();
    }//GEN-LAST:event_btTimKiemActionPerformed

    private void ckbThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbThanhToanActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int ret = JOptionPane.showConfirmDialog(this,"Bạn có muốn đăng xuất?","Thông báo",JOptionPane.YES_NO_OPTION);
        if(ret == JOptionPane.YES_OPTION){
            DangNhap dn = new DangNhap();
            dn.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btThongBaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThongBaoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ThongBaoSV tbSV = new ThongBaoSV();
        tbSV.setVisible(true);
    }//GEN-LAST:event_btThongBaoActionPerformed

    private void btTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTBActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ThongBaoSV tbSV = new ThongBaoSV();
        tbSV.setVisible(true);
    }//GEN-LAST:event_btTBActionPerformed

    private void btYeuCauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btYeuCauActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        YeuCauSV yeucauSV = new YeuCauSV();
        yeucauSV.setVisible(true);
    }//GEN-LAST:event_btYeuCauActionPerformed

    private void btYCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btYCActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        YeuCauSV yeucauSV = new YeuCauSV();
        yeucauSV.setVisible(true);
    }//GEN-LAST:event_btYCActionPerformed

    private void btViPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViPhamActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ViPhamSV viphamSV = new ViPhamSV();
        viphamSV.setVisible(true);
    }//GEN-LAST:event_btViPhamActionPerformed

    private void btVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVPActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ViPhamSV viphamSV = new ViPhamSV();
        viphamSV.setVisible(true);
    }//GEN-LAST:event_btVPActionPerformed

    private void btCuTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCuTruActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SVCuTru ctSV = new SVCuTru();
        ctSV.setVisible(true);
    }//GEN-LAST:event_btCuTruActionPerformed

    private void btCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCTActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SVCuTru ctSV = new SVCuTru();
        ctSV.setVisible(true);
    }//GEN-LAST:event_btCTActionPerformed

    private void btHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHoaDonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HoaDonSV hoadonSV = new HoaDonSV();
        hoadonSV.setVisible(true);
    }//GEN-LAST:event_btHoaDonActionPerformed

    private void btHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHDActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HoaDonSV hoadonSV = new HoaDonSV();
        hoadonSV.setVisible(true);
    }//GEN-LAST:event_btHDActionPerformed

    private void btHoatDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHoatDongActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HoatDongSV hoatdongSV = new HoatDongSV();
        hoatdongSV.setVisible(true);
    }//GEN-LAST:event_btHoatDongActionPerformed

    private void btHoatDong2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHoatDong2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HoatDongSV hoatdongSV = new HoatDongSV();
        hoatdongSV.setVisible(true);
    }//GEN-LAST:event_btHoatDong2ActionPerformed

    private void btTraCuuPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTraCuuPhongActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TraCuuPhongSV tcpSV = new TraCuuPhongSV();
        tcpSV.setVisible(true);
    }//GEN-LAST:event_btTraCuuPhongActionPerformed

    private void btTCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTCPActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TraCuuPhongSV tcpSV = new TraCuuPhongSV();
        tcpSV.setVisible(true);
    }//GEN-LAST:event_btTCPActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        CapNhatTTSV cnttSV = new CapNhatTTSV();
        cnttSV.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    public void thietlapManHinh() {
        tb = new DefaultTableModel();
        String tieuDe[] = {"Loại hóa đơn", "Mã Phòng", "Giá tiền", "Ngày lập hóa đơn", "Hạn thanh toán", "Ngày thanh toán"};
        tb.setColumnIdentifiers(tieuDe);
        tbHD.setModel(tb);
        setVisible(true);
        
        String[] itemsFilterLoaiHD = {"Loại hóa đơn", "Sua chua", "Tien dien", "Tien nuoc", "Tien phong"};
        
        DefaultComboBoxModel<String> insertLoaiHD = new DefaultComboBoxModel<>(itemsFilterLoaiHD);
        cbLoaiHD.setModel(insertLoaiHD);

    }
    
    public void layDSHoaDon() {
        String maHD = txtMaHD.getText();
        String loaiHDFilter = (String) cbLoaiHD.getSelectedItem();
        boolean ckThanhToan = ckbThanhToan.isSelected();
                
        Connection con = getConnection();
        if (con == null) {
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu", "Error", JOptionPane.ERROR_MESSAGE);
        }
            
        try {           
            StringBuilder sql = new StringBuilder("SELECT MAHOADON, H.MAPHONG, SOTIEN, LOAIHOADON, NGAYLAPHOADON, HANTHANHTOAN, NGAYTHANHTOAN "
                    + "FROM HOADON H RIGHT JOIN (SELECT * FROM CUTRU WHERE MSSV = ?) C ON H.MAPHONG = C.MAPHONG WHERE H.MSSV = ? OR H.MSSV IS NULL");
            if (!maHD.isEmpty()) {
                sql.append(" AND MAHOADON = ?");
            }
            if (!"Default".equals(loaiHDFilter)) {
                sql.append(" AND LOAIHOADON = ?");
            }
            if(ckThanhToan) {
                sql.append(" AND NGAYTHANHTOAN IS NULL");
            }
            sql.append(" ORDER BY MAHOADON");

            PreparedStatement pstmt = con.prepareStatement(sql.toString());
            pstmt.setString(1, mssv);
            pstmt.setString(2, mssv);
            
            int parameterIndex = 3;
            if (!maHD.isEmpty()) {
                pstmt.setString(parameterIndex++, maHD);
            }
            if (!"Default".equals(loaiHDFilter)) {
                pstmt.setString(parameterIndex++, loaiHDFilter);
            }
            ResultSet rs = pstmt.executeQuery();
            
            tb.setRowCount(0); // Clear table
            while (rs.next()) {
                String maHoaDon = rs.getString("MAHOADON");
                String maP = rs.getString("MAPHONG");
                String loaiHD = rs.getString("LOAIHOADON");
                String tienHD = rs.getString("SOTIEN");
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                Date ngaylap = rs.getDate("NGAYLAPHOADON");
                String ngLHD = sdf.format(ngaylap);
                String hanHD = sdf.format(rs.getDate("HANTHANHTOAN"));
                String ngTT = "";
                if(rs.getString("NGAYTHANHTOAN") != null)
                    ngTT = convertDateFormat(rs.getString("NGAYTHANHTOAN"));
                tb.addRow(new Object[]{maHoaDon, loaiHD, maP, tienHD, ngLHD, hanHD, ngTT});
            }
            rs.close();
            pstmt.close();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi trong quá trình truy vấn cơ sở dữ liệu", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btCT;
    private javax.swing.JButton btCuTru;
    private javax.swing.JButton btHD;
    private javax.swing.JButton btHoaDon;
    private javax.swing.JButton btHoatDong;
    private javax.swing.JButton btHoatDong2;
    private javax.swing.JButton btTB;
    private javax.swing.JButton btTCP;
    private javax.swing.JButton btThongBao;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btTraCuuPhong;
    private javax.swing.JButton btVP;
    private javax.swing.JButton btViPham;
    private javax.swing.JButton btYC;
    private javax.swing.JButton btYeuCau;
    private javax.swing.JComboBox<String> cbLoaiHD;
    private javax.swing.JCheckBox ckbThanhToan;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbAnhWebDev;
    private javax.swing.JLabel lbBL;
    private javax.swing.JLabel lbBL1;
    private javax.swing.JLabel lbGhiChuTTHD;
    private javax.swing.JLabel lbTTHD;
    private javax.swing.JTable tbHD;
    private javax.swing.JTextField txtMaHD;
    // End of variables declaration//GEN-END:variables
}
