/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SinhVienMoi;

import NhanVienKeToan.TrangChuKT;
import com.mycompany.qlktx.CapNhatCuTru;
import com.mycompany.qlktx.DSSinhVien;
import static com.mycompany.qlktx.QLKTX.*;
import com.mycompany.qlktx.DangNhap;
import com.mycompany.qlktx.QLThongBao;
import com.mycompany.qlktx.QLViPham;
import com.mycompany.qlktx.QLYeuCau;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ThongBaoSV extends javax.swing.JFrame {
    String mssv = DangNhap.GlobalVariables.username;
    //String mssv = "00520001";
    /**
     * Creates new form ThongBao
     */
    private DefaultTableModel tbThongBao;
    public ThongBaoSV() {
        initComponents();
        setSize(1512, 1024);
        thietlapManHinh();
        layDSThongBao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbAnhWebDev = new javax.swing.JLabel();
        btBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbTB = new javax.swing.JLabel();
        lbTK = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblThongBao = new javax.swing.JTable();
        btTimKiem = new javax.swing.JButton();
        txtThongBao = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        javax.swing.JLabel lbChucNang1 = new javax.swing.JLabel();
        btDangXuat = new javax.swing.JButton();
        btThongBao = new javax.swing.JButton();
        btTB = new javax.swing.JButton();
        btYeuCau = new javax.swing.JButton();
        btYC = new javax.swing.JButton();
        btViPham = new javax.swing.JButton();
        btVP = new javax.swing.JButton();
        btCuTru = new javax.swing.JButton();
        btCT = new javax.swing.JButton();
        btHoaDon = new javax.swing.JButton();
        btHD = new javax.swing.JButton();
        btHoatDong = new javax.swing.JButton();
        btHoatDong2 = new javax.swing.JButton();
        btTraCuuPhong = new javax.swing.JButton();
        btTCP = new javax.swing.JButton();
        btThongTinCaNhan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 80));

        lbAnhWebDev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAnhWebDev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.jpg"))); // NOI18N

        btBack.setBackground(new java.awt.Color(254, 254, 254));
        btBack.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btBack.setForeground(new java.awt.Color(255, 255, 255));
        btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Back.png"))); // NOI18N
        btBack.setBorder(null);
        btBack.setBorderPainted(false);
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btBack)
                .addGap(624, 624, 624)
                .addComponent(lbAnhWebDev)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btBack)
                .addGap(21, 21, 21))
            .addComponent(lbAnhWebDev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 80));

        lbTB.setBackground(new java.awt.Color(255, 255, 255));
        lbTB.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbTB.setForeground(new java.awt.Color(83, 160, 219));
        lbTB.setText("Thông Báo");

        lbTK.setBackground(new java.awt.Color(255, 255, 255));
        lbTK.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbTK.setForeground(new java.awt.Color(86, 86, 86));
        lbTK.setText("Tìm kiếm nội dung:");

        tblThongBao.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tblThongBao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nội dung thông báo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblThongBao);

        btTimKiem.setBackground(new java.awt.Color(93, 163, 217));
        btTimKiem.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btTimKiem.setText("Tìm Kiếm");
        btTimKiem.setActionCommand("");
        btTimKiem.setBorder(null);
        btTimKiem.setBorderPainted(false);
        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });

        txtThongBao.setBackground(new java.awt.Color(240, 240, 240));
        txtThongBao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtThongBao.setForeground(new java.awt.Color(86, 86, 86));
        txtThongBao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtThongBao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThongBaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addComponent(lbTB))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbTK)
                                .addGap(18, 18, 18)
                                .addComponent(txtThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbTB)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(350, 309));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbChucNang1.setBackground(new java.awt.Color(255, 255, 255));
        lbChucNang1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lbChucNang1.setForeground(new java.awt.Color(83, 160, 219));
        lbChucNang1.setText("Menu");
        jPanel8.add(lbChucNang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 25, -1, -1));

        btDangXuat.setBackground(new java.awt.Color(254, 254, 254));
        btDangXuat.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/solar--logout-2-outline (1).png"))); // NOI18N
        btDangXuat.setText("  Đăng xuất");
        btDangXuat.setBorder(null);
        btDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btDangXuat.setMaximumSize(new java.awt.Dimension(167, 50));
        btDangXuat.setMinimumSize(new java.awt.Dimension(167, 50));
        btDangXuat.setName("Dangxuat"); // NOI18N
        btDangXuat.setPreferredSize(new java.awt.Dimension(167, 50));
        btDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDangXuatActionPerformed(evt);
            }
        });
        jPanel8.add(btDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 200, 60));

        btThongBao.setBackground(new java.awt.Color(254, 254, 254));
        btThongBao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ThongBao.png"))); // NOI18N
        btThongBao.setBorder(null);
        btThongBao.setOpaque(true);
        btThongBao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThongBaoActionPerformed(evt);
            }
        });
        jPanel8.add(btThongBao, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 95, 62, 64));

        btTB.setBackground(new java.awt.Color(254, 254, 254));
        btTB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btTB.setForeground(new java.awt.Color(86, 86, 86));
        btTB.setText("Thông báo");
        btTB.setBorder(null);
        btTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTBActionPerformed(evt);
            }
        });
        jPanel8.add(btTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 111, 131, -1));

        btYeuCau.setBackground(new java.awt.Color(254, 254, 254));
        btYeuCau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/YeuCau.png"))); // NOI18N
        btYeuCau.setBorder(null);
        btYeuCau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btYeuCauActionPerformed(evt);
            }
        });
        jPanel8.add(btYeuCau, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 165, 55, 58));

        btYC.setBackground(new java.awt.Color(254, 254, 254));
        btYC.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btYC.setText("Yêu cầu");
        btYC.setBorder(null);
        btYC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btYCActionPerformed(evt);
            }
        });
        jPanel8.add(btYC, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 179, 103, -1));

        btViPham.setBackground(new java.awt.Color(254, 254, 254));
        btViPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ViPham.png"))); // NOI18N
        btViPham.setBorder(null);
        btViPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViPhamActionPerformed(evt);
            }
        });
        jPanel8.add(btViPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 229, 63, 55));

        btVP.setBackground(new java.awt.Color(254, 254, 254));
        btVP.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btVP.setText("Vi phạm");
        btVP.setBorder(null);
        btVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVPActionPerformed(evt);
            }
        });
        jPanel8.add(btVP, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 246, 100, -1));

        btCuTru.setBackground(new java.awt.Color(254, 254, 254));
        btCuTru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CuTru.png"))); // NOI18N
        btCuTru.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btCuTru.setOpaque(true);
        btCuTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCuTruActionPerformed(evt);
            }
        });
        jPanel8.add(btCuTru, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 290, 62, 57));

        btCT.setBackground(new java.awt.Color(254, 254, 254));
        btCT.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btCT.setText("Cư trú");
        btCT.setBorder(null);
        btCT.setOpaque(true);
        btCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCTActionPerformed(evt);
            }
        });
        jPanel8.add(btCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 84, -1));

        btHoaDon.setBackground(new java.awt.Color(254, 254, 254));
        btHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/HoaDon.png"))); // NOI18N
        btHoaDon.setBorder(null);
        btHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHoaDonActionPerformed(evt);
            }
        });
        jPanel8.add(btHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 353, 60, 60));

        btHD.setBackground(new java.awt.Color(254, 254, 254));
        btHD.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btHD.setText("Hóa đơn");
        btHD.setBorder(null);
        btHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHDActionPerformed(evt);
            }
        });
        jPanel8.add(btHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 110, -1));

        btHoatDong.setBackground(new java.awt.Color(254, 254, 254));
        btHoatDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CongDong.png"))); // NOI18N
        btHoatDong.setBorder(null);
        btHoatDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHoatDongActionPerformed(evt);
            }
        });
        jPanel8.add(btHoatDong, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 419, 68, -1));

        btHoatDong2.setBackground(new java.awt.Color(254, 254, 254));
        btHoatDong2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btHoatDong2.setText("Hoạt động");
        btHoatDong2.setBorder(null);
        btHoatDong2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHoatDong2ActionPerformed(evt);
            }
        });
        jPanel8.add(btHoatDong2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 130, -1));

        btTraCuuPhong.setBackground(new java.awt.Color(254, 254, 254));
        btTraCuuPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TraCuu 50x50.png"))); // NOI18N
        btTraCuuPhong.setBorder(null);
        btTraCuuPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTraCuuPhongActionPerformed(evt);
            }
        });
        jPanel8.add(btTraCuuPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 50, 50));

        btTCP.setBackground(new java.awt.Color(254, 254, 254));
        btTCP.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btTCP.setText("Tra cứu phòng");
        btTCP.setBorder(null);
        btTCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTCPActionPerformed(evt);
            }
        });
        jPanel8.add(btTCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 170, -1));

        btThongTinCaNhan.setBackground(new java.awt.Color(254, 254, 254));
        btThongTinCaNhan.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btThongTinCaNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fluent--person-20-filled.png"))); // NOI18N
        btThongTinCaNhan.setText("Thông tin cá nhân");
        btThongTinCaNhan.setBorder(null);
        btThongTinCaNhan.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btThongTinCaNhan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btThongTinCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThongTinCaNhanActionPerformed(evt);
            }
        });
        jPanel8.add(btThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1550, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        this.dispose();
        TrangChuSV trangchuSV = new TrangChuSV();
        trangchuSV.setVisible(true);
    }//GEN-LAST:event_btBackActionPerformed

    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
        layDSThongBao();
    }//GEN-LAST:event_btTimKiemActionPerformed

    private void btDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangXuatActionPerformed
        int ret = JOptionPane.showConfirmDialog(this,"Bạn có muốn đăng xuất?","Thông báo",JOptionPane.YES_NO_OPTION);
        if(ret == JOptionPane.YES_OPTION){
            DangNhap dn = new DangNhap();
            dn.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btDangXuatActionPerformed

    private void btThongBaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThongBaoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ThongBaoSV tbSV = new ThongBaoSV();
        tbSV.setVisible(true);
    }//GEN-LAST:event_btThongBaoActionPerformed

    private void btTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTBActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ThongBaoSV tbSV = new ThongBaoSV();
        tbSV.setVisible(true);
    }//GEN-LAST:event_btTBActionPerformed

    private void btYeuCauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btYeuCauActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        YeuCauSV yeucauSV = new YeuCauSV();
        yeucauSV.setVisible(true);
    }//GEN-LAST:event_btYeuCauActionPerformed

    private void btYCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btYCActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        YeuCauSV yeucauSV = new YeuCauSV();
        yeucauSV.setVisible(true);
    }//GEN-LAST:event_btYCActionPerformed

    private void btViPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViPhamActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ViPhamSV viphamSV = new ViPhamSV();
        viphamSV.setVisible(true);
    }//GEN-LAST:event_btViPhamActionPerformed

    private void btVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVPActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ViPhamSV viphamSV = new ViPhamSV();
        viphamSV.setVisible(true);
    }//GEN-LAST:event_btVPActionPerformed

    private void btCuTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCuTruActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        CuTruSV ctSV = new CuTruSV();
        ctSV.setVisible(true);
    }//GEN-LAST:event_btCuTruActionPerformed

    private void btCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCTActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SVCuTru ctSV = new SVCuTru();
        ctSV.setVisible(true);
    }//GEN-LAST:event_btCTActionPerformed

    private void btHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHoaDonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HoaDonSV hoadonSV = new HoaDonSV();
        hoadonSV.setVisible(true);
    }//GEN-LAST:event_btHoaDonActionPerformed

    private void btHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHDActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HoaDonSV hoadonSV = new HoaDonSV();
        hoadonSV.setVisible(true);
    }//GEN-LAST:event_btHDActionPerformed

    private void btHoatDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHoatDongActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HoatDongSV hoatdongSV = new HoatDongSV();
        hoatdongSV.setVisible(true);
    }//GEN-LAST:event_btHoatDongActionPerformed

    private void btHoatDong2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHoatDong2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HoatDongSV hoatdongSV = new HoatDongSV();
        hoatdongSV.setVisible(true);
    }//GEN-LAST:event_btHoatDong2ActionPerformed

    private void btTraCuuPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTraCuuPhongActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TraCuuPhongSV tcpSV = new TraCuuPhongSV();
        tcpSV.setVisible(true);
    }//GEN-LAST:event_btTraCuuPhongActionPerformed

    private void btTCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTCPActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TraCuuPhongSV tcpSV = new TraCuuPhongSV();
        tcpSV.setVisible(true);
    }//GEN-LAST:event_btTCPActionPerformed

    private void btThongTinCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThongTinCaNhanActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        CapNhatTTSV cnttSV = new CapNhatTTSV();
        cnttSV.setVisible(true);
    }//GEN-LAST:event_btThongTinCaNhanActionPerformed

    private void txtThongBaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThongBaoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ThongBaoSV tbSV = new ThongBaoSV();
        tbSV.setVisible(true);
    }//GEN-LAST:event_txtThongBaoActionPerformed
    
    private void thietlapManHinh() {
        tbThongBao = new DefaultTableModel();
        String tieuDe1[] = {"Nội dung"};
        tbThongBao.setColumnIdentifiers(tieuDe1);
        tblThongBao.setModel(tbThongBao);
        setVisible(true);
    }

    private void layDSThongBao() {
        String ndTimKiem = txtThongBao.getText();
        
        Connection con = getConnection();
        if (con == null) {
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu", "Error", JOptionPane.ERROR_MESSAGE);
        }
            
        try {           
            StringBuilder sql = new StringBuilder("SELECT NOIDUNG FROM THONGBAO WHERE MANGUOINHAN IS NULL OR MANGUOINHAN = ?");
            if (!ndTimKiem.isEmpty()) {
                ndTimKiem = "%" + ndTimKiem + "%";
                sql.append(" AND NOIDUNG LIKE ?");
            }
            sql.append(" ORDER BY MATHONGBAO");
                       
            
            PreparedStatement pstmt = con.prepareStatement(sql.toString());
            pstmt.setString(1, mssv);
            if (!ndTimKiem.isEmpty()) {
                pstmt.setString(2, ndTimKiem);
            }
            ResultSet rs = pstmt.executeQuery();
            
            tbThongBao.setRowCount(0); // Clear table
            while (rs.next()) {
                String ndTB = rs.getString("NOIDUNG");
                tbThongBao.addRow(new Object[]{ndTB});
            }
            
            rs.close();
            pstmt.close();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi trong quá trình truy vấn cơ sở dữ liệu1", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btCT;
    private javax.swing.JButton btCuTru;
    private javax.swing.JButton btDangXuat;
    private javax.swing.JButton btHD;
    private javax.swing.JButton btHoaDon;
    private javax.swing.JButton btHoatDong;
    private javax.swing.JButton btHoatDong2;
    private javax.swing.JButton btTB;
    private javax.swing.JButton btTCP;
    private javax.swing.JButton btThongBao;
    private javax.swing.JButton btThongTinCaNhan;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btTraCuuPhong;
    private javax.swing.JButton btVP;
    private javax.swing.JButton btViPham;
    private javax.swing.JButton btYC;
    private javax.swing.JButton btYeuCau;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbAnhWebDev;
    private javax.swing.JLabel lbTB;
    private javax.swing.JLabel lbTK;
    private javax.swing.JTable tblThongBao;
    private javax.swing.JTextField txtThongBao;
    // End of variables declaration//GEN-END:variables

    
}
